name: galaksi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  geolocator: ^14.0.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  form_builder_validators: ^11.1.2
  cloud_firestore: ^5.6.7
  material_symbols_icons: ^4.2815.0
  basic_utils: ^5.8.2
  collection: ^1.19.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
